### ISSUE TITLE
会出现大量这种错误，能看看是什么问题麽？

### ISSUE THREAD

**Issue by jzp820927** [cnbeining/Chrome-Data-Compression-Proxy-Standalone-Python#1]
![image](https://cloud.githubusercontent.com/assets/5740066/15430944/29b513aa-1eda-11e6-971d-e5aa0ccc9800.png)

会出现大量这种错误，能看看是什么问题麽？

**Comment by jzp820927** [comment]
但是这些错误链接，在单独的新标签页又能打开。

**Comment by cnbeining** [comment]
啧 我没能复现啊。。。

**Comment by jzp820927** [comment]
好吧，我只是举个例。大概就是链接中带中文字符的。

**Comment by cnbeining** [comment]
啊 新的Chrome更新了。

我去源码里面扒扒吧。

**Comment by cnbeining** [comment]
另外我要严肃提醒一句：

你有可能需要的安全和匿名性 此项目**不能提供**。

请务必清楚此点。

**Comment by jzp820927** [comment]
我本来还说再试试，复现一下，现在运行直接报错了:

python google.py
Traceback (most recent call last):
  File "google.py", line 163, in <module>
    server = ThreadingHTTPServer(server_address, Handler)
  File "/usr/lib/python2.7/SocketServer.py", line 414, in **init**
    self.socket_type)
  File "/usr/lib/python2.7/socket.py", line 191, in **init**
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 97] Address family not supported by protocol

**Comment by cnbeining** [comment]
请务必**完全退出** 。

我推了个fix上去，再试试吧。

**Comment by jzp820927** [comment]
我是直接 kill pid 的，难道还有什么守护进程
行吧，我再试试，谢谢

**Comment by cnbeining** [comment]
没有啊...我真没复现（

2016年6月18日星期六，天朝屁民 notifications@github.com 写道：

**Comment by jzp820927** [comment]
还是这个报错，奇怪了，之前都可以正常运行的，我重启下系统试试吧

**Comment by jzp820927** [comment]
不行，重启了，还是这个报错，找不到原因了。
系统环境是 ubuntu server 16.04 
python 版本：python --version
Python 2.7.11+

**Comment by cnbeining** [comment]
stackoverflow下还没什么效果。

我只能猜是网卡那边在捣乱了...

2016年6月18日星期六，天朝屁民 notifications@github.com 写道：

**Comment by jzp820927** [comment]
我换了台电脑，能不能运行了，但是又报下面的错：

Exception happened during processing of request from ('::ffff:192.168.1.2', 54787, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in **init**
    self.handle()
  File "google.py", line 79, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "google.py", line 109, in sogouProxy
    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'

**Comment by cnbeining** [comment]
Python版本不够。

必须Python 2.7.9以上。

**Comment by jzp820927** [comment]
应该是，下面这个 py 才 296，不过上面那个 py 版本是最新的，我自己找下原因吧，不知道是不是修改了什么核心参数造成的。

**Comment by jzp820927** [comment]
@cnbeining 你好，再来反应下问题，编码问题，莫名其妙就好了，不知道是啥原因。
而且"socket.error: [Errno 97] Address family not supported by protocol"，这个报错，我也找到原因了，是因为我把 IPv6 禁用了，就会报这个错。能不能麻烦你看下，为什么禁用 IPv6 会报这个错？能不能修复下？因为我这边没有 IPv6 环境，所以没启用。
